name: travel_concierge
description: Travel Concierge - Your AI-powered travel companion

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  google_maps_flutter: ^2.7.0
  google_places_flutter: ^2.0.9
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  permission_handler: ^11.3.1
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
    - family: Andika
      fonts:
        - asset: assets/fonts/AndikaRegular.ttf
          weight: 400

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/img_group_170.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/img_group_170.png"
    background_color: "#FF0373"
    theme_color: "#FF0373"
  windows:
    generate: true
    image_path: "assets/images/img_group_170.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/img_group_170.png"
